import { Category, DentoIroPalette, Product, Tag } from '../types';

export const DENTO_IRO_PALETTES: DentoIroPalette[] = [
  {
    id: 'sakura',
    name: 'Sakura-iro',
    japaneseName: 'さくらいろ',
    kanji: '桜色',
    character: '桜',
    primaryColor: '#E87A90',
    bgColor: '#FAF6F7',
    borderColor: '#EFE3E6',
    description: 'Warna kelopak bunga sakura yang lembut, memancarkan ketenangan dan keanggunan musim semi.',
    philosophy: 'Mono no aware (物の哀れ)',
    meaning: 'Apresiasi mendalam terhadap keindahan sesaat, kelembutan hati, dan pembaruan harapan hidup.',
  },
  {
    id: 'nadeshiko',
    name: 'Nadeshiko-iro',
    japaneseName: 'なでしこいろ',
    kanji: '撫子色',
    character: '撫',
    primaryColor: '#EE7989',
    bgColor: '#FCF7F8',
    borderColor: '#EFE2E5',
    description: 'Warna bunga anyelir liar Jepang, melambangkan kelembutan hati dan pesona feminin klasik.',
    philosophy: 'Yamato Nadeshiko (大和撫子)',
    meaning: 'Ketabahan anggun wanita, kelembutan budi pekerti, dan kesetiaan yang tak pernah luntur.',
  },
  {
    id: 'toki',
    name: 'Toki-iro',
    japaneseName: 'ときいろ',
    kanji: '鴇色',
    character: '鴇',
    primaryColor: '#F4A7B9',
    bgColor: '#FAF4F5',
    borderColor: '#EFE4E6',
    description: 'Warna semu merah muda dari bulu sayap burung ibis jambul khas Jepang.',
    philosophy: 'Miyabi (雅)',
    meaning: 'Kehalusan estetika bangsawan istana kuno, penuh kedamaian batin dan kehangatan romantis.',
  },
  {
    id: 'wakatake',
    name: 'Wakatake-iro',
    japaneseName: 'わかたけいろ',
    kanji: '若竹色',
    character: '竹',
    primaryColor: '#5BA983',
    bgColor: '#F5F8F6',
    borderColor: '#DFEAE3',
    description: 'Warna kesegaran batang bambu muda dan teh hijau matcha yang menyejukkan jiwa.',
    philosophy: 'Seijaku (静寂)',
    meaning: 'Ketenteraman dan kejernihan pikiran, ketahanan lentur dalam menghadapi dinamika hidup.',
  },
  {
    id: 'fuji',
    name: 'Fuji-iro',
    japaneseName: 'ふじいろ',
    kanji: '藤色',
    character: '藤',
    primaryColor: '#8B81C3',
    bgColor: '#F7F6FA',
    borderColor: '#E4E1EF',
    description: 'Warna ungu lavender anggun dari untaian bunga wisteria Jepang yang mekar di musim semi.',
    philosophy: 'Yugen (幽玄)',
    meaning: 'Pesona mendalam yang tak kasat mata, martabat bangsawan, dan misteri keindahan spiritual.',
  },
  {
    id: 'rikyucha',
    name: 'Rikyu-cha',
    japaneseName: 'りきゅうちゃ',
    kanji: '利休茶',
    character: '茶',
    primaryColor: '#897858',
    bgColor: '#F9F8F5',
    borderColor: '#EBE6DC',
    description: 'Warna teh tradisi upacara teh Sen no Rikyu, nuansa earthy wabi-sabi yang tenang.',
    philosophy: 'Wabi-Sabi (侘寂)',
    meaning: 'Kesederhanaan yang bersahaja, menemukan keutuhan dalam ketidaksempurnaan alami.',
  },
  {
    id: 'kohaku',
    name: 'Kohaku-iro',
    japaneseName: 'こはくいろ',
    kanji: '琥珀色',
    character: '琥',
    primaryColor: '#CA7853',
    bgColor: '#FBF7F4',
    borderColor: '#EFE6E0',
    description: 'Warna hangat batu ambar berkilau keemasan, menghadirkan kehangatan dan keabadian.',
    philosophy: 'Nukumori (温もり)',
    meaning: 'Kenyamanan abadi dan kehangatan sanubari seperti cahaya lentera senja di Kyoto.',
  },
  {
    id: 'shinbashi',
    name: 'Shinbashi-iro',
    japaneseName: 'しんばしいろ',
    kanji: '新橋色',
    character: '橋',
    primaryColor: '#0089A7',
    bgColor: '#F4F9FB',
    borderColor: '#DDEBF0',
    description: 'Warna toska biru-hijau modis era Meiji yang dipopulerkan oleh geisha distrik Shinbashi di Tokyo.',
    philosophy: 'Iki (粋)',
    meaning: 'Keanggunan berkelas, kemandirian modern, dan kesegaran air telaga pegunungan.',
  },
  {
    id: 'yamabuki',
    name: 'Yamabuki-iro',
    japaneseName: 'やまぶきいろ',
    kanji: '山吹色',
    character: '吹',
    primaryColor: '#E9A328',
    bgColor: '#FDFBF6',
    borderColor: '#F3EBD8',
    description: 'Warna kuning emas bunga mawar Jepang liar yang tumbuh di tepi aliran sungai jernih.',
    philosophy: 'Hikari (光)',
    meaning: 'Cahaya optimisme ceria, kemakmuran batin, dan pancaran pesona kebahagiaan sejati.',
  },
  {
    id: 'akane',
    name: 'Akane-iro',
    japaneseName: 'あかねいろ',
    kanji: '茜色',
    character: '茜',
    primaryColor: '#B7282E',
    bgColor: '#FAF5F5',
    borderColor: '#EFE0E1',
    description: 'Warna merah mawar tua dari akar tanaman madder, warna langit senja yang menggetarkan sukma.',
    philosophy: 'Tasogare (黄昏)',
    meaning: 'Kekuatan tekad mulia, kehangatan asmara klasik, dan kedalaman jiwa yang teguh.',
  },
];

export const INITIAL_CATEGORIES: Category[] = [];

export const INITIAL_TAGS: Tag[] = [];

export const INITIAL_PRODUCTS: Product[] = [];
